### ISSUE TITLE
Latest Chrome Beta 116.0.5845.82 breaks Catppuccin themes

### ISSUE THREAD

**Issue by Jubijub** [catppuccin/chrome#12]
Chrome version : Version 116.0.5845.82 (Official Build) beta (64-bit) (from google-chrome-beta Arch package)

Catppuccin Chrome Macchiato extension : latest from Chrome Web Store (3.1), or latest unpacked from source (commit 62e6c4433bbf23e4cdbdedaa1c3a8b0670c92b40 )

Steps to reproduce : 
- install the extension on the latest Chrome Beta
- Notice that the active and passive tabs have the exact same background color (despite the manifest saying otherwise)
- Notice that there is no visual demarcation between the tabs anymore
- Active tab is only denoted by a slightly brighter text

![2023-08-12_18-15](https://github.com/catppuccin/chrome/assets/1254368/439e5054-2dc1-4d8d-ac97-3d20ac1b8bbe)

**Comment by r-nl** [comment]
Have observed the same issue, theme is unusable on the newest chrome redesign.

**Comment by johnzzon** [comment]
Yeah, other than a slightly lighter font in the tab name, it's impossible to distinguish the active tab.

Google Chrome Version 118.0.5993.88 (Official Build) (64-bit)

**Comment by r-nl** [comment]
@isabelincorp @punidramesh , Thought it'd be worth bringing back up that this theme is currently unusable on stable chrome.

**Comment by elkrien** [comment]
> @isabelincorp @punidramesh , Thought it'd be worth bringing back up that this theme is currently unusable on stable chrome.

Can You write more specific what is wrong? I'm using stable chrome and everything works OK with this theme. Yes, active tab is  only denoted by a slightly brighter text but it is very visible (at least on good monitors). What it should look like? You want completely different color of tabs?

**Comment by elkrien** [comment]
OK, I've updated repo with new version that is fixing all the issues. Working on updating Chrome Web Store. I will close that issue when store is updated.

**Comment by johnzzon** [comment]
Looks great again now! Thanks for fixing it :)
