### ISSUE TITLE
Theme missing

### ISSUE THREAD

**Issue by AVMiraga** [catppuccin/chrome#19]
It seems like Catppuccin theme got removed from Google Webstore.

**Comment by uncenter** [comment]
The links in the README all go to valid Chrome extensions that I can view, is there an issue with installing them or?

**Comment by AVMiraga** [comment]
![image](https://github.com/user-attachments/assets/6efe1356-4e79-4920-89a9-a17daaaf7f68)
I get this error. ;l

**Comment by uncenter** [comment]
Might be a region issue with where it can be published, whereabouts are you located?

**Comment by AVMiraga** [comment]
Oh god it is region related, why even a theme is blocked in a region... Blocked here in Azerbaijan unfortunately :(

**Comment by uncenter** [comment]
Actually, it looks like we can enable it:

![CleanShot 2024-10-21 at 14 35 13](https://github.com/user-attachments/assets/7a3b44cb-e925-495d-93d1-a643a08ab4bb)

(screenshot from the distribution page of a different extension)

I'll try to get this changed in a moment.

**Comment by uncenter** [comment]
Unfortunately I don't think we can get this changed at this time but for now have you tried installing manually? See https://github.com/catppuccin/chrome#manual-installation.

**Comment by AVMiraga** [comment]
> Unfortunately I don't think we can get this changed at this time but for now have you tried installing manually? See https://github.com/catppuccin/chrome#manual-installation.

Yea I managed to get it through manual installation. By the way, like a month ago it was there in theme shop without any problems. Thanks though!
