### ISSUE TITLE
Publish to Chrome Web Store

### ISSUE THREAD

**Issue by tuhanayim** [catppuccin/chrome#2]
please 🙂

**Comment by geekyBoogiepop** [comment]
I agree, this is a must for getting theme updates.

**Comment by elkrien** [comment]
I cannot promise anything but I will try to do it. Don't have a google developer account yet and this will be my first time so need to read more first.

**Comment by elkrien** [comment]
Theme is Chrome Web store so closing issue.

**Comment by Mange** [comment]
…and here's a link for anyone else subscribing. :-)
https://chrome.google.com/webstore/detail/catppuccin-chrome-theme/cmpdlhmnmjhihmcfnigoememnffkimlk
