### ISSUE TITLE
Some Visual Issues

### ISSUE THREAD

**Issue by tuhanayim** [catppuccin/chrome#3]
## ~~search bar is not colored~~ normal behavior. chrome themes don't supports coloring context menus colors.
![image](https://user-images.githubusercontent.com/83988414/152655268-91c7b616-7c0f-409e-9f09-6e1ec7e4e687.png)

## not sure about this one but i think its theme problem. 
![image](https://user-images.githubusercontent.com/83988414/152655273-35ca561e-1933-41ea-b391-4d8ba6104a9d.png)

## quick links background is not colored
![image](https://user-images.githubusercontent.com/83988414/152655318-a14066c1-bd8e-4ba0-b04c-3874dbc63f6d.png)

**Comment by tuhanayim** [comment]
## link hover thingy not colored
![image](https://user-images.githubusercontent.com/83988414/152655551-5a75f8e3-0303-46c4-b5ca-964912135d62.png)

**Comment by elkrien** [comment]
OK. So not everything can be customized in Chrome unfortunately:
1. Search bar - Chrome doesn't support coloring 
2. Gmail and Images links - corrected
3. Quick links - corrected 
4. Link hover - to be honest don't know how to change it. I haven't found which parameter is responsible for this (checked all that i use). Will try to dig more.

**Comment by elkrien** [comment]
OK, I think I managed to color link hoover - it depends on frames so cannot be different but it looks better now (that's all I can do). I have also completely changed theme code and added more dark version. Both are available in the repo - I decided to keep them both to let people choose. I will leave this issue still open to test and if there will be no other bugs I will close it.

**Comment by elkrien** [comment]
OK, for now I consider that all above is corrected so I close the issue.
