### ISSUE TITLE
Better contrast with foreground and background tab

### ISSUE THREAD

**Issue by geekyBoogiepop** [catppuccin/chrome#4]
Firefox vs Brave
![image](https://user-images.githubusercontent.com/32626891/175134122-d1d1ac5f-7e8b-4903-8e9c-3fd7c327d934.png)

Is it possible to add an outline to the foreground tab? Something similar to the Firefox variant. Another alternative would be to add a line at the bottom of the foreground tab to make a better contrast with the background tabs, take a look at these examples:
![image](https://user-images.githubusercontent.com/32626891/175134416-c54c15d8-d6e0-4b86-8d85-1b240aab34d8.png)

https://github.com/doki-theme/doki-theme-web

**Comment by elkrien** [comment]
It is possible but what color should it be? If I choose for example peach somebody else will ask for blue :)
I didn't use it because I didn't want to create all color variant as it is with Firefox theme: 4 catppuccin flavours x 15 colors = 60 themes to maintain and update. 
It's too much for me ;)

**Comment by elkrien** [comment]
OK. I will try to do something and will see how it looks. Just give me 2-3 days to find some time for this.

**Comment by geekyBoogiepop** [comment]
Thank you so much 🥰🙏

**Comment by elkrien** [comment]
OK, I tried and it looks that with highlight it is required to do separate themes for Chrome, Brave and Edge (I haven't tried Chromium). This is strange but the same manifest.json file looks different in Chrome and in other browsers. 
This is how Chrome looks like:
![image](https://user-images.githubusercontent.com/78103450/175786647-97e779bb-66f6-48d6-873a-e14cdca3d4ec.png)
And this is Brave:
![image](https://user-images.githubusercontent.com/78103450/175786625-89be7adb-3cfb-4dc1-a4e1-d93a5c101c6f.png)

In Chrome it is OK, only tab is highligted and in Brave or Edge the whole toolbar. To do it correctly separate themes are required for each browser. I don't want to promise that I will do it - right now I'm too busy to do it in near future.
Maybe someone else will do it and submit PR to this repo - I will be very happy to merge it.

**Comment by geekyBoogiepop** [comment]
Thank you for taking the time and look into it 🙏 I could work on the Brave theme on my spare time, don't know where to start, though, do you have any resources that I can look into and understand how the theming works?

**Comment by elkrien** [comment]
You can try on Google developer page but to be honest it's difficult to find some good information. 
My way of understanding how theme works was to take some good theme, maybe some of the one You linked:

https://github.com/doki-theme/doki-theme-web

and just edit manifest.json file step by step. Good idea is to change colour in each line for some specific one that will not be used in Your theme (for me it was red) and then load theme and see what was changed. And in this way step by step You see how it works.

**Comment by geekyBoogiepop** [comment]
Ok. Thank you. I will update this thread is something happens.

**Comment by elkrien** [comment]
In new version I think active and inactive tabs are more visually identified. I'm closing this issue.
