### ISSUE TITLE
Support for Colour Accents

### ISSUE THREAD

**Issue by cpressland** [catppuccin/chrome#7]
It'd be great to have the colour accents that are available on the [Firefox](https://github.com/catppuccin/firefox) version of this theme. Thats the only thing I miss when using Edge instead of Firefox for work.

<img width="592" alt="Screenshot 2022-10-29 at 11 16 26" src="https://user-images.githubusercontent.com/6557665/198825997-d155c732-1b0e-40ae-b7b8-6bc45d45d56a.png">

**Comment by punidramesh** [comment]
@elkrien Is there any way for us to edit/generate the .pak file with our preferred accent?

**Comment by elkrien** [comment]
> @elkrien Is there any way for us to edit/generate the .pak file with our preferred accent?

You don't need to edit/generate .pak file. You need to edit manifest.json. Just:

- Clone this repository locally
- Edit manifest.json with changing colors You need (omnibox_text and ntp_link probably for accent)
- Open Chrome/Edge/Brave
- Type chrome://extensions in the address bar
- Select the "Developer mode" checkbox
- Click the "Load unpacked" button
- Choose the selected theme directory

**Comment by punidramesh** [comment]
Can we add this in the README?

**Comment by hiyorijl** [comment]
> - Edit manifest.json with changing colors You need (omnibox_text and ntp_link probably for accent)

if you change omni_text you get inverted colors on the color bg of the search bar
