### ISSUE TITLE
Inactive window tab header color contrast

### ISSUE THREAD

**Issue by nemkin** [catppuccin/chrome#8]
I'm using the Mocha variant of this theme.

The inactive tab header fonts turn darker when the window itself becomes inactive (e.g. a small window is in front of it).

See the Github text on the second tab:

Active:
![image](https://user-images.githubusercontent.com/25765636/220093835-13514e4d-0732-4281-a22f-8c88224725ef.png)

Inactive:
![image](https://user-images.githubusercontent.com/25765636/220093888-0dcf6c09-8d86-4b70-a7a9-da6329568c3e.png)

I think the inactive state has so little contrast the text is barely readable for a lot of people. It would be better if the colors didn't change in an inactive window state.

**Comment by elkrien** [comment]
It is something that cannot be themed unfortunately.

**Comment by nemkin** [comment]
> It is something that cannot be themed unfortunately.

I see, thank you :)
